name: passwd
description: A beautiful and secure password manager.
version: 2.1.3
maintainer: rustzz
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.7
  archive: ^3.3.4
  async_redux: any
  base_x: ^2.0.0
  biometric_storage: ^4.1.3
  cached_network_image: ^3.2.2
  crypto: ^3.0.2
  cryptography: ^2.0.5
  otp: ^3.1.3
  desktop_window: ^0.4.0
  dio: ^4.0.6
  encrypt: ^5.0.1
  ez_localization: ^1.0.0+2
  flutter_icons: ^1.1.0
  flutter_otp_text_field: ^1.1.1
  flutter_secure_storage: ^6.0.0
  functional_data: ^1.0.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  injectable: ^1.5.4
  logging: ^1.1.0
  logging_appenders: ^1.0.0
  msgpack_dart: ^1.0.0
  path: ^1.8.2
  path_provider: ^2.0.11
  percent_indicator: ^4.2.2
  pinenacl: ^0.5.1
  provider: ^6.0.4
  provider_for_redux: ^5.0.0
  responsive_builder: ^0.4.3
  share: ^2.0.4
  shared_preferences: ^2.0.15
  supercharged: ^2.1.1
  tuple: ^2.0.1
  url_launcher: ^6.1.6
  flutter_autofill_service: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  flutter_launcher_icons: ^0.11.0
  functional_data_generator: ^1.1.4
  injectable_generator: ^1.5.5
  lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/languages/
    - assets/ca/

flutter_icons:
  android: true
  ios: true
  image_path_ios: assets/icons/ios.png
  image_path_android: assets/icons/android.png
  image_path: assets/icons/ios.png
  adaptive_icon_background: assets/icons/adaptive_bg.png
  adaptive_icon_foreground: assets/icons/adaptive_fg.png
