name: autofill_service_example
description: Demonstrates how to use the autofill_service plugin.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  autofill_service:
    path: ../
  flutter:
    sdk: flutter
  logging: ^1.0.0
  logging_appenders: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

